Add support for Redis Sentinels
WiIIiam278/HuskSync pull request #216
Opened 2023-12-11 04:38 UTC by romanalexander

2023-12-11 11:03 UTC, WiIIiam278 requested changes
Interesting, but fair enough - happy to add this sort of thing if users are using it. One small request that'd also be neat for this PR: A config option to change the database No. (currently hardcoded to ID0)

2023-12-15 22:58 UTC, romanalexander commented on common/src/main/java/net/william278/husksync/config/Settings.java
> +    private String redisSentinelMaster = "";
👍

2023-12-15 23:05 UTC, romanalexander commented
> Interesting, fair enough - happy to add this sort of thing if users are using it. Thanks for your work!
> 
> One small request that'd also be neat for this PR: A config option to change the database number (currently is hardcoded to 0)

Redis PubSub doesn't respect database numbers, so the channels would need to be changed to separate them out to not have strange cross-contamination issues. This could break existing plugins if they subscribe directly to the topics for behavior.

Also additionally some Redis topologies don't support database numbers which could cause confusion.

2023-12-16 03:47 UTC, WiIIiam278 commented
Interesting, understood - best left as is then :)

2023-12-19 19:25 UTC, WiIIiam278 approved these changes

2023-12-19 19:27 UTC, merged