hotfix(Bukkit): fix death sync event when setting health of 0
WiIIiam278/HuskSync pull request #37
Opened 2022-07-12 23:12 UTC by HookWoods

This fix sync failed when we set to player the health of 0 hp, which call the PlayerDeathEvent in async, while the event need to be called sync

2022-07-12 23:18 UTC, WiIIiam278 requested changes
Looks good - just one tiny thing. Need to run a few tests with this to make sure it doesn't cause any issues with synchronization on death.

2022-07-12 23:18 UTC, WiIIiam278 commented on bukkit/src/main/java/net/william278/husksync/player/BukkitPlayer.java
> +                    double healthToSet = currentHealth > currentMaxHealth ? currentMaxHealth : statusData.health;
Probably should be `final double`

2022-07-12 23:47 UTC, WiIIiam278 commented
Going to need to prevent the death we invoke here from dropping player items I think - probably by adding a death event listener to the EventListener and removing item drops if the player is still synchronising, otherwise we'll get dupes.

2022-07-13 07:55 UTC, HookWoods commented
> Going to need to prevent the death we invoke here from dropping player items I think - probably by adding a death event listener to the EventListener and removing item drops if the player is still synchronising, otherwise we'll get dupes.

Do we have a solution to know if player is already sync ? Or just by using the usersAwaitingSync ?
And also, would it not be better to refactor the isDead function to ensure player health <= 0 || playerData.health <= 0 ?

2022-07-13 08:07 UTC, WiIIiam278 commented
usersAwaitingSync, yep.
If you think refactoring will be cleaner, sure. Up to you really.

2022-07-13 11:22 UTC, merged