Save and show server id/name where snaphot was created
WiIIiam278/HuskSync pull request #54
Opened 2022-10-14 23:31 UTC by NeadApTar

Probably some users, like me and my moderators, didn't have enough information on which server the saving of player data was created. I added this feature to display the server name in the list of snapshots or in the manager. In the future, it will also be convenient to output to GUI.

Unfortunately, I don't know how to make the plugin itself add a new column to the database, so PR needs to be updated with this option.

2023-02-22 13:08 UTC, WiIIiam278 requested changes
I previously discussed this change with you on Discord, so apologies for giving it so long before leaving a review.

On the double, I actually do like this feature quite a bit -- I think I previously had concerns over storing the server in json along with the save cause or something for better organisation, but tbh that doesn't seem particularly necessary in hindsight.

Would probably need to write a migrator for the DB as mentioned.

2023-02-22 13:08 UTC, WiIIiam278 commented on common/src/main/java/net/william278/husksync/data/DataServerID.java
> +    public static String setServerID(@NotNull String server) {
Not fond of static methods for stuff like this, would rather see this String be accessed through a getter in the HuskSync plugin interface directly

2023-02-22 13:08 UTC, WiIIiam278 commented on common/src/main/java/net/william278/husksync/data/DataServerID.java
> +    @SerializedName("server_id")
Are we serializing this anywhere? Not sure this is needed unless we are, and I think we're just storing the server as a string.

2023-02-22 13:08 UTC, WiIIiam278 commented on common/src/main/java/net/william278/husksync/data/DataServerID.java
> +public class DataServerID {
I think this should probably be a `@YamlDocument` saved in the user's config directory where the user has to enter the server ID.

2023-02-22 13:08 UTC, WiIIiam278 commented on common/src/main/resources/locales/ja-jp.yml
> +data_manager_server: '[❖ %1%](#fb06c5-#E37dfd show_text=&7サーバー ID:\n&8スナップショットが作成されたサーバー)\n'
For locales, best copy over the english locale -- leave TL up to contributors as MTL is unreliable

2023-02-22 13:08 UTC, WiIIiam278 commented on common/src/main/resources/database/mysql_schema.sql
> +    `server_id`    varchar(32) NOT NULL,
I think just `server` would be fine here to avoid ambiguity with actual numerical/unique ID fields

2023-02-22 13:08 UTC, WiIIiam278 commented on common/src/main/java/net/william278/husksync/config/Settings.java
> +    public String serverID = "node-1";
As mentioned, probably best have DataServerID save this in its own YamlDocument-based file, as this breaks users managing their config with symlinks

2023-02-22 16:43 UTC, iVillager commented
I added this feature to HuskSync 2 weeks ago xD

2023-02-22 16:45 UTC, iVillager commented
https://github.com/FlexDojo/HuskSync/commit/f443753c453f316c20acc1c2c236ed36c32f4e85

2023-07-01 12:14 UTC, WiIIiam278 commented
Closing this as stale for now. I actually do quite like this feature & it has grown on me; I guess my concerns stem from 
- the fact it's relatively minor and requires the user to actively configure more (setting a server ID manually on each server, etc)
- the implementation required adding columns to the database and didn't do migrations and used some statics to store this so, which slightly goes against the OO design I was going for 
If you can address these concerns and rebase, I'd be happy to look at this PR again. Thanks for your interest :)

2023-07-01 12:14 UTC, closed without merging